Vagrant.configure("2") do |config|
  config.vm.define "course_db" do |course_db|
    course_db.vm.box = "generic/ubuntu2204"
    course_db.vm.network "private_network", ip: "192.168.33.50"
    course_db.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 2
      libvirt.driver = "kvm"
      libvirt.storage_pool_name = "default"
      libvirt.storage_pool_path = "/var/lib/libvirt/images"
      libvirt.uri = "qemu:///system"
    end
    course_db.vm.provision "shell", inline: "usermod -aG sudo vagrant"

    course_db.vm.provision "ansible" do |ansible|
      ansible.limit = "course_db"
      ansible.playbook = "course_db.yml"
      ansible.extra_vars = {
        ansible_password: "root"
      }
    end
  end
  
  
end

